{% set name = "openmetadata-ingestion" %}
{% set version = "1.1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openmetadata-ingestion-{{ version }}.tar.gz
  sha256: f8f8aeaf6db216ccd76e17feb28218174956d2c11c51dac4f7bbc4f960c1b137

build:
#  entry_points:
#    - metadata = metadata.cmd:metadata
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - setuptools >=65.6.3
    - google-auth >=1.33.0
    - pymysql >=1.0.2
    - jsonpatch >=1.32
    - requests >=2.23
    - requests-aws4auth >=1.1,<2.0
    - cached-property >=1.5.0
#    - grpcio-tools >=1.40.0  # Causes run time issues with Python 37
#    - antlr4-python3-runtime >=4.9.2 # Causes run time issues with Python 37 use newer feedstock
#      https://github.com/conda-forge/antlr-python-runtime-feedstock/blob/main/recipe/meta.yaml
    - antlr-python-runtime >=4.7.2
    - pyyaml
    - tabulate >=0.9.0
    - jinja2 >=2.11.3
    - typing-extensions #<=4.5.0
    - commonregex
    - python-dateutil >=2.8.1
    - sqlalchemy >=1.4.0,<2
    - avro-python3 >=1.10.2,<2.0
    - croniter >=1.3.0,<1.4.0
    - cryptography
    - importlib-metadata >=4.11.0,<4.13.0
    - wheel >=0.36.2,<0.39.0
    - mypy_extensions >=0.4.3
    - openmetadata-sqllineage >=1.0.4
    - pydantic >=1.9.0,<2.0
    - chardet >=4.0.0
    - boto3 >=1.19.12,<2.0
    - idna >=2.5,<3
    - email-validator >=1.0.3
    - googlesearch >=3.0.0
    - python-jose >=3.3.0,<4.0
    - typing_inspect
    - typing-compat >=0.1.0,<0.2.0
    - jsonschema
#    - botocore >=1.22.12
#    - sqllineage >=1.3.7
#    - pandas >=1.3.5


test:
  imports:
    - airflow_provider_openmetadata
    - metadata

about:
  home: https://open-metadata.org/
  summary: Ingestion Framework for OpenMetadata
  dev_url: https://github.com/open-metadata/OpenMetadata
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
